### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by KenioCarvalho** [ibm-watson-iot/functions#298] opened 2020-10-22 11:56 UTC
Try to install on a new jupyter notebook i get the following error

Collecting git+git://github.com/ibm-watson-iot/functions.git@production
  Cloning git://github.com/ibm-watson-iot/functions.git (to revision production) to /private/var/folders/81/h69f2rfd2fn71p7_gnsh1mdh0000gn/T/pip-req-build-4h99zqa6
Requirement already satisfied, skipping upgrade: dill==0.3.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from iotfunctions==2.0.3) (0.3.0)
Requirement already satisfied, skipping upgrade: ibm-cos-sdk==2.1.3 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from iotfunctions==2.0.3) (2.1.3)
Requirement already satisfied, skipping upgrade: numpy>=1.17.3 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from iotfunctions==2.0.3) (1.18.5)
Requirement already satisfied, skipping upgrade: pandas>=0.24.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from iotfunctions==2.0.3) (1.1.3)
Requirement already satisfied, skipping upgrade: scikit-learn==0.20.3 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from iotfunctions==2.0.3) (0.20.3)
Requirement already satisfied, skipping upgrade: scipy>=1.1.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from iotfunctions==2.0.3) (1.5.2)
Requirement already satisfied, skipping upgrade: requests==2.23.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from iotfunctions==2.0.3) (2.23.0)
Requirement already satisfied, skipping upgrade: urllib3==1.24.3 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from iotfunctions==2.0.3) (1.24.3)
Requirement already satisfied, skipping upgrade: ibm_db==3.0.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from iotfunctions==2.0.3) (3.0.1)
Requirement already satisfied, skipping upgrade: ibm_db_sa==0.3.3 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from iotfunctions==2.0.3) (0.3.3)
Collecting lxml==4.3.4
  Using cached lxml-4.3.4.tar.gz (2.5 MB)
Collecting lightgbm>=2.3.1
  Using cached lightgbm-3.0.0-py2.py3-none-macosx_10_13_x86_64.macosx_10_14_x86_64.macosx_10_15_x86_64.whl (1.0 MB)
Collecting nose>=1.3.7
  Using cached nose-1.3.7-py3-none-any.whl (154 kB)
Collecting psycopg2-binary==2.8.4
  Using cached psycopg2_binary-2.8.4-cp38-cp38-macosx_10_9_x86_64.macosx_10_9_intel.macosx_10_10_intel.macosx_10_10_x86_64.whl (1.5 MB)
Processing /Users/keniocarvalho/Library/Caches/pip/wheels/d0/64/9f/1630b48562dc6f42097398c5c505ac13012d9a44b1223e658d/pyod-0.7.5-py3-none-any.whl
Collecting scikit-image>=0.16.2
  Using cached scikit_image-0.17.2-cp38-cp38-macosx_10_13_x86_64.whl (12.2 MB)
Requirement already satisfied, skipping upgrade: sqlalchemy==1.3.10 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from iotfunctions==2.0.3) (1.3.10)
Processing /Users/keniocarvalho/Library/Caches/pip/wheels/99/a3/9b/e06c89f3752b8ad6834f79c08a0886c947948a578cf27b6816/tabulate-0.8.5-py3-none-any.whl
Requirement already satisfied, skipping upgrade: ibm-cos-sdk-core==2.*,>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from ibm-cos-sdk==2.1.3->iotfunctions==2.0.3) (2.7.0)
Requirement already satisfied, skipping upgrade: ibm-cos-sdk-s3transfer==2.*,>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from ibm-cos-sdk==2.1.3->iotfunctions==2.0.3) (2.7.0)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.7.3 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from pandas>=0.24.0->iotfunctions==2.0.3) (2.8.1)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from pandas>=0.24.0->iotfunctions==2.0.3) (2020.1)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests==2.23.0->iotfunctions==2.0.3) (2020.6.20)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests==2.23.0->iotfunctions==2.0.3) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from requests==2.23.0->iotfunctions==2.0.3) (2.10)
Requirement already satisfied, skipping upgrade: six in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from pyod==0.7.5->iotfunctions==2.0.3) (1.15.0)
Collecting numba>=0.35
  Using cached numba-0.51.2-cp38-cp38-macosx_10_14_x86_64.whl (2.2 MB)
Requirement already satisfied, skipping upgrade: joblib in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from pyod==0.7.5->iotfunctions==2.0.3) (0.17.0)
Requirement already satisfied, skipping upgrade: matplotlib in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from pyod==0.7.5->iotfunctions==2.0.3) (3.3.2)
Requirement already satisfied, skipping upgrade: pillow!=7.1.0,!=7.1.1,>=4.3.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from scikit-image>=0.16.2->iotfunctions==2.0.3) (7.2.0)
Collecting imageio>=2.3.0
  Using cached imageio-2.9.0-py3-none-any.whl (3.3 MB)
Collecting PyWavelets>=1.1.1
  Using cached PyWavelets-1.1.1-cp38-cp38-macosx_10_9_x86_64.whl (4.3 MB)
Collecting networkx>=2.0
  Using cached networkx-2.5-py3-none-any.whl (1.6 MB)
Collecting tifffile>=2019.7.26
  Using cached tifffile-2020.10.1-py3-none-any.whl (152 kB)
Requirement already satisfied, skipping upgrade: jmespath<1.0.0,>=0.7.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from ibm-cos-sdk-core==2.*,>=2.0.0->ibm-cos-sdk==2.1.3->iotfunctions==2.0.3) (0.10.0)
Requirement already satisfied, skipping upgrade: docutils<0.16,>=0.10 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from ibm-cos-sdk-core==2.*,>=2.0.0->ibm-cos-sdk==2.1.3->iotfunctions==2.0.3) (0.15.2)
Requirement already satisfied, skipping upgrade: setuptools in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from numba>=0.35->pyod==0.7.5->iotfunctions==2.0.3) (47.1.0)
Collecting llvmlite<0.35,>=0.34.0.dev0
  Using cached llvmlite-0.34.0-cp38-cp38-macosx_10_9_x86_64.whl (18.4 MB)
Requirement already satisfied, skipping upgrade: kiwisolver>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from matplotlib->pyod==0.7.5->iotfunctions==2.0.3) (1.2.0)
Requirement already satisfied, skipping upgrade: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from matplotlib->pyod==0.7.5->iotfunctions==2.0.3) (0.10.0)
Requirement already satisfied, skipping upgrade: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from matplotlib->pyod==0.7.5->iotfunctions==2.0.3) (2.4.7)
Requirement already satisfied, skipping upgrade: decorator>=4.3.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from networkx>=2.0->scikit-image>=0.16.2->iotfunctions==2.0.3) (4.4.2)
Building wheels for collected packages: iotfunctions, lxml
  Building wheel for iotfunctions (setup.py) ... done
  Created wheel for iotfunctions: filename=iotfunctions-2.0.3-py3-none-any.whl size=187059 sha256=21423cf96f73fe0c6f23553e0f7fc39bb32d2033b0201667c02f3bab67b1c249
  Stored in directory: /private/var/folders/81/h69f2rfd2fn71p7_gnsh1mdh0000gn/T/pip-ephem-wheel-cache-2a8xo4ql/wheels/d4/25/53/11b4f9b0e9a08d12fd6ce4d72332b70599d10901643e7c9ca8
  Building wheel for lxml (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/81/h69f2rfd2fn71p7_gnsh1mdh0000gn/T/pip-install-2ea9vber/lxml/setup.py'"'"'; __file__='"'"'/private/var/folders/81/h69f2rfd2fn71p7_gnsh1mdh0000gn/T/pip-install-2ea9vber/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/81/h69f2rfd2fn71p7_gnsh1mdh0000gn/T/pip-wheel-l3efch2p
       cwd: /private/var/folders/81/h69f2rfd2fn71p7_gnsh1mdh0000gn/T/pip-install-2ea9vber/lxml/
  Complete output (260 lines):
  Building lxml version 4.3.4.
  Building without Cython.
  Using build configuration of libxslt 1.1.33
  Building against libxml2/libxslt in the following directory: /opt/anaconda2/lib
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.8
  creating build/lib.macosx-10.9-x86_64-3.8/lxml
  copying src/lxml/_elementpath.py -> build/lib.macosx-10.9-x86_64-3.8/lxml
  copying src/lxml/sax.py -> build/lib.macosx-10.9-x86_64-3.8/lxml
  copying src/lxml/pyclasslookup.py -> build/lib.macosx-10.9-x86_64-3.8/lxml
  copying src/lxml/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/lxml
  copying src/lxml/builder.py -> build/lib.macosx-10.9-x86_64-3.8/lxml
  copying src/lxml/doctestcompare.py -> build/lib.macosx-10.9-x86_64-3.8/lxml
  copying src/lxml/usedoctest.py -> build/lib.macosx-10.9-x86_64-3.8/lxml
  copying src/lxml/cssselect.py -> build/lib.macosx-10.9-x86_64-3.8/lxml
  copying src/lxml/ElementInclude.py -> build/lib.macosx-10.9-x86_64-3.8/lxml
  creating build/lib.macosx-10.9-x86_64-3.8/lxml/includes
  copying src/lxml/includes/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/lxml/includes
  creating build/lib.macosx-10.9-x86_64-3.8/lxml/html
  copying src/lxml/html/soupparser.py -> build/lib.macosx-10.9-x86_64-3.8/lxml/html
  copying src/lxml/html/defs.py -> build/lib.macosx-10.9-x86_64-3.8/lxml/html
  copying src/lxml/html/_setmixin.py -> build/lib.macosx-10.9-x86_64-3.8/lxml/html
  copying src/lxml/html/clean.py -> build/lib.macosx-10.9-x86_64-3.8/lxml/html
  copying src/lxml/html/_diffcommand.py -> build/lib.macosx-10.9-x86_64-3.8/lxml/html
  copying src/lxml/html/html5parser.py -> build/lib.macosx-10.9-x86_64-3.8/lxml/html
  copying src/lxml/html/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/lxml/html
  copying src/lxml/html/formfill.py -> build/lib.macosx-10.9-x86_64-3.8/lxml/html
  copying src/lxml/html/builder.py -> build/lib.macosx-10.9-x86_64-3.8/lxml/html
  copying src/lxml/html/ElementSoup.py -> build/lib.macosx-10.9-x86_64-3.8/lxml/html
  copying src/lxml/html/_html5builder.py -> build/lib.macosx-10.9-x86_64-3.8/lxml/html
  copying src/lxml/html/usedoctest.py -> build/lib.macosx-10.9-x86_64-3.8/lxml/html
  copying src/lxml/html/diff.py -> build/lib.macosx-10.9-x86_64-3.8/lxml/html
  creating build/lib.macosx-10.9-x86_64-3.8/lxml/isoschematron
  copying src/lxml/isoschematron/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/lxml/isoschematron
  copying src/lxml/etree.h -> build/lib.macosx-10.9-x86_64-3.8/lxml
  copying src/lxml/etree_api.h -> build/lib.macosx-10.9-x86_64-3.8/lxml
  copying src/lxml/lxml.etree.h -> build/lib.macosx-10.9-x86_64-3.8/lxml
  copying src/lxml/lxml.etree_api.h -> build/lib.macosx-10.9-x86_64-3.8/lxml
  copying src/lxml/includes/xmlerror.pxd -> build/lib.macosx-10.9-x86_64-3.8/lxml/includes
  copying src/lxml/includes/c14n.pxd -> build/lib.macosx-10.9-x86_64-3.8/lxml/includes
  copying src/lxml/includes/xmlschema.pxd -> build/lib.macosx-10.9-x86_64-3.8/lxml/includes
  copying src/lxml/includes/__init__.pxd -> build/lib.macosx-10.9-x86_64-3.8/lxml/includes
  copying src/lxml/includes/schematron.pxd -> build/lib.macosx-10.9-x86_64-3.8/lxml/includes
  copying src/lxml/includes/tree.pxd -> build/lib.macosx-10.9-x86_64-3.8/lxml/includes
  copying src/lxml/includes/uri.pxd -> build/lib.macosx-10.9-x86_64-3.8/lxml/includes
  copying src/lxml/includes/etreepublic.pxd -> build/lib.macosx-10.9-x86_64-3.8/lxml/includes
  copying src/lxml/includes/xpath.pxd -> build/lib.macosx-10.9-x86_64-3.8/lxml/includes
  copying src/lxml/includes/htmlparser.pxd -> build/lib.macosx-10.9-x86_64-3.8/lxml/includes
  copying src/lxml/includes/xslt.pxd -> build/lib.macosx-10.9-x86_64-3.8/lxml/includes
  copying src/lxml/includes/config.pxd -> build/lib.macosx-10.9-x86_64-3.8/lxml/includes
  copying src/lxml/includes/xmlparser.pxd -> build/lib.macosx-10.9-x86_64-3.8/lxml/includes
  copying src/lxml/includes/xinclude.pxd -> build/lib.macosx-10.9-x86_64-3.8/lxml/includes
  copying src/lxml/includes/dtdvalid.pxd -> build/lib.macosx-10.9-x86_64-3.8/lxml/includes
  copying src/lxml/includes/relaxng.pxd -> build/lib.macosx-10.9-x86_64-3.8/lxml/includes
  copying src/lxml/includes/lxml-version.h -> build/lib.macosx-10.9-x86_64-3.8/lxml/includes
  copying src/lxml/includes/etree_defs.h -> build/lib.macosx-10.9-x86_64-3.8/lxml/includes
  creating build/lib.macosx-10.9-x86_64-3.8/lxml/isoschematron/resources
  creating build/lib.macosx-10.9-x86_64-3.8/lxml/isoschematron/resources/rng
  copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.macosx-10.9-x86_64-3.8/lxml/isoschematron/resources/rng
  creating build/lib.macosx-10.9-x86_64-3.8/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.macosx-10.9-x86_64-3.8/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.macosx-10.9-x86_64-3.8/lxml/isoschematron/resources/xsl
  creating build/lib.macosx-10.9-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.macosx-10.9-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.macosx-10.9-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.macosx-10.9-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.macosx-10.9-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.macosx-10.9-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.macosx-10.9-x86_64-3.8/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  running build_ext
  building 'lxml.etree' extension

**Comment by herleraja** [comment] 2020-11-23 16:05
Seems to be a duplicate of https://github.ibm.com/wiotp/monitoring-dashboard/issues/1559

**Closed by herleraja** 2020-11-23 16:05 UTC
